spring.application.name=vector-db
spring.ai.vertex.project-id=<YOUR_PROJECT_ID>
spring.ai.vertex.location=us-central1
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always